#!/usr/bin/env bash
# 备份功能单元测试
# 测试 iptctl 的备份和恢复功能

set -euo pipefail

# 加载测试辅助函数
source ../test_helpers.sh

# 测试函数：test_backup_functions
test_backup_functions() {
    print_info "开始备份功能测试..."
    
    # 设置测试环境
    setup_test_env
    
    # 加载 iptctl 脚本
    source "$TEST_TEMP_DIR/iptctl_test.sh"
    
    # 测试 1: 备份目录创建
    print_info "测试 1: 备份目录创建"
    
    # 模拟 root 用户（备份到 /var/backups/iptctl）
    local backup_dir="/var/backups/iptctl"
    
    # 测试备份目录检测函数（如果存在）
    if declare -f get_backup_dir >/dev/null; then
        local dir=$(get_backup_dir)
        assert_contains "$dir" "iptctl" "备份目录应包含 iptctl"
    else
        print_warning "get_backup_dir 函数未找到，跳过测试"
    fi
    
    # 测试 2: 备份文件命名
    print_info "测试 2: 备份文件命名"
    
    # 创建测试备份文件
    local timestamp=$(date +%Y%m%d_%H%M%S)
    local backup_file="$TEST_TEMP_DIR/backup_${timestamp}.rules"
    
    echo "# 测试备份规则" > "$backup_file"
    assert_file_exists "$backup_file" "备份文件应创建成功"
    
    # 验证文件内容
    local content=$(cat "$backup_file")
    assert_contains "$content" "测试备份规则" "备份文件应包含正确内容"
    
    # 测试 3: 备份计数和清理
    print_info "测试 3: 备份计数和清理"
    
    # 创建多个备份文件
    for i in {1..3}; do
        echo "# 备份文件 $i" > "$TEST_TEMP_DIR/backup_${i}.rules"
    done
    
    # 统计备份文件数量
    local backup_count=$(ls "$TEST_TEMP_DIR"/*.rules 2>/dev/null | wc -l)
    assert_equal "3" "$backup_count" "应创建 3 个备份文件"
    
    # 测试 4: 备份恢复验证
    print_info "测试 4: 备份恢复验证"
    
    # 创建包含特定规则的备份文件
    cat > "$TEST_TEMP_DIR/test_backup.rules" << 'EOF'
# Generated by iptctl
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -i lo -j ACCEPT
-A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
COMMIT
EOF
    
    # 验证备份文件格式
    local backup_content=$(cat "$TEST_TEMP_DIR/test_backup.rules")
    assert_contains "$backup_content" "*filter" "备份文件应包含 filter 表"
    assert_contains "$backup_content" "COMMIT" "备份文件应包含 COMMIT"
    assert_contains "$backup_content" "ESTABLISHED,RELATED" "备份文件应包含连接状态规则"
    
    # 测试 5: 备份完整性检查
    print_info "测试 5: 备份完整性检查"
    
    # 创建无效备份文件
    echo "无效内容" > "$TEST_TEMP_DIR/invalid_backup.rules"
    
    # 验证文件大小（简单完整性检查）
    local valid_size=$(wc -c < "$TEST_TEMP_DIR/test_backup.rules")
    local invalid_size=$(wc -c < "$TEST_TEMP_DIR/invalid_backup.rules")
    
    assert_not_equal "$valid_size" "$invalid_size" "有效和无效备份文件大小应不同"
    
    # 测试 6: 会话备份管理
    print_info "测试 6: 会话备份管理"
    
    # 创建会话备份目录结构
    local session_dir="$TEST_TEMP_DIR/session_$(date +%s)"
    mkdir -p "$session_dir"
    
    # 模拟会话备份文件
    echo "# 会话备份" > "$session_dir/rules.v4"
    echo "# IPv6 规则" > "$session_dir/rules.v6"
    
    # 验证会话备份结构
    assert_file_exists "$session_dir/rules.v4" "会话应包含 IPv4 规则文件"
    assert_file_exists "$session_dir/rules.v6" "会话应包含 IPv6 规则文件"
    
    # 清理测试环境
    cleanup_test_env
    
    print_success "备份功能测试完成"
    return 0
}

# 测试函数：test_persistence_functions
test_persistence_functions() {
    print_info "开始持久化功能测试..."
    
    setup_test_env
    
    # 加载 iptctl 脚本
    source "$TEST_TEMP_DIR/iptctl_test.sh"
    
    # 测试 1: 持久化方式检测
    print_info "测试 1: 持久化方式检测"
    
    # 模拟不同系统的持久化工具
    local persistence_tools=("netfilter-persistent" "iptables-services" "systemd")
    
    for tool in "${persistence_tools[@]}"; do
        print_info "测试持久化工具: $tool"
        
        # 这里可以模拟工具存在性检测
        # 实际 iptctl 中会有相应的检测逻辑
    done
    
    # 测试 2: 规则保存验证
    print_info "测试 2: 规则保存验证"
    
    # 创建模拟的规则文件
    local rules_file="$TEST_TEMP_DIR/rules.v4"
    cat > "$rules_file" << 'EOF'
# 测试规则
-A INPUT -p tcp --dport 22 -j ACCEPT
-A INPUT -p tcp --dport 80 -j ACCEPT
-A INPUT -j DROP
EOF
    
    # 验证规则文件格式
    local rule_count=$(grep -c "^-A" "$rules_file" || echo "0")
    assert_equal "3" "$rule_count" "规则文件应包含 3 条规则"
    
    # 测试 3: 自动安装检测
    print_info "测试 3: 自动安装检测"
    
    # 模拟包管理器检测
    local package_managers=("apt-get" "dnf" "yum")
    
    for pm in "${package_managers[@]}"; do
        if command -v "$pm" >/dev/null 2>&1; then
            print_info "检测到包管理器: $pm"
            # 这里可以测试自动安装逻辑
        fi
    done
    
    cleanup_test_env
    
    print_success "持久化功能测试完成"
    return 0
}

# 如果直接运行此脚本，则执行测试
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    test_backup_functions
    test_persistence_functions
    print_test_summary
fi